const headerTags = [
  "Find your Boo!",
  "Swipe right to find your spark!",
  "Connecting hearts, one swipe at a time.",
  "Your journey to love starts here.",
  "Flirting with destiny, swiping with purpose.",
  "Unleash your charm and swipe away!",
  "Because finding love should be an adventure.",
  "Discover meaningful connections through swipes.",
  "Matching souls, one swipe closer.",
  "Bringing love and technology together.",
  "Swipe, match, and let the magic begin.",
  "Ghosting the singles scene? Swipe to haunt their heart!",
  "Spiriting away your loneliness, one swipe at a time.",
  "Searching for an otherworldly connection? Swipe away!",
  "Join our spectral singles in the afterlove!",
  "Eternally searching for love? Swipe right!",
  "Unmask your ghostly allure with every swipe.",
  "A haunted romance awaits – start swiping!",
  "Are you ready for some paranormal match-making?",
  "Let your heart be the compass on this ghostly journey.",
  "Matching phantoms and hearts since forever.",
];

const headerGreetings = [
  "Hi",
  "Hello",
  "Hey",
  "Sup",
  "Yo",
  "Greetings",
  "Salutations",
  "Howdy",
  "Aloha",
  "Bonjour",
  "Hola",
  "Ciao",
  "Namaste",
  "Salaam",
  "Shalom",
  "Konnichiwa",
  "Ni Hao",
  "Guten Tag",
  "Privet",
  "Anyoung Haseyo",
  "Sawasdee",
  "Merhaba",
  "Jambo",
  "Salam",
  "Selamat Siang",
  "Kamusta",
  "Sveiki",
  "Szia",
  "Hej",
  "Hoi",
  "Hallo",
  "Hei",
  "Hej",
  "Halo",
  "Helo",
  "Olá",
  "Zdravstvuyte",
  "Zdravo",
  "Salam",
  "Sannu",
  "Sveiki",
  "Szia",
];
export { headerTags, headerGreetings };
